# Generated by Django 5.0.6 on 2024-05-09 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('cantidad_tickets', models.IntegerField()),
                ('codigo', models.CharField(max_length=3)),
                ('estado', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'En curso'), (2, 'Finalizado')], default=0)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rifas_creadas', to='rifas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(max_length=10)),
                ('es_ganador', models.BooleanField(default=False)),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='rifas.rifa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rifas', to='rifas.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='rifa',
            name='usuarios_participantes',
            field=models.ManyToManyField(related_name='rifas_participadas', through='rifas.UsuarioRifa', to='rifas.usuario'),
        ),
    ]
